# Generated by Django 5.2.5 on 2025-09-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
