# Generated by Django 5.2.5 on 2025-09-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField(blank=True)),
                ('color', models.CharField(default='#fff8e1', max_length=20)),
                ('position_x', models.IntegerField(default=10)),
                ('position_y', models.IntegerField(default=10)),
            ],
        ),
    ]
