# Generated by Django 5.2.5 on 2025-09-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickynote',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
