# Generated by Django 5.2.5 on 2025-09-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('available', '空席'), ('occupied', '利用中'), ('reserved', '予約')], default='available', max_length=10)),
                ('people', models.IntegerField(blank=True, null=True)),
                ('entryTime', models.DateTimeField(blank=True, null=True)),
                ('exitTime', models.DateTimeField(blank=True, null=True)),
                ('memo', models.TextField(blank=True)),
            ],
        ),
    ]
